# Generated by Django 5.0.1 on 2024-01-29 19:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateTimeField()),
                ('event_place', models.JSONField(default=dict)),
                ('event_member', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('user_type', models.CharField(max_length=255)),
                ('user_data', models.JSONField(default=dict)),
                ('token_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_expires', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
