# Generated by Django 5.0.1 on 2024-01-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_owner',
            field=models.JSONField(default=dict),
        ),
    ]
