# Generated by Django 5.0.1 on 2024-01-30 05:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_event_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_owner', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_type', models.CharField(max_length=255)),
                ('user_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='token',
            name='user_data',
        ),
        migrations.RemoveField(
            model_name='token',
            name='user_type',
        ),
        migrations.AddField(
            model_name='token',
            name='token_owner',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_expires',
            field=models.DateTimeField(),
        ),
    ]
