# Generated by Django 5.0.1 on 2024-01-30 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_user_remove_token_user_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
