# Generated by Django 5.0.1 on 2024-01-30 06:08

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_delete_category_delete_event_delete_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category_name', models.CharField(max_length=255)),
                ('category_owner', models.JSONField()),
                ('category_date', models.DateTimeField(default=datetime.datetime(2024, 1, 30, 6, 8, 28, 222986, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_owner', models.JSONField(default=dict)),
                ('event_member', models.JSONField(default=dict)),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateTimeField()),
                ('event_place', models.JSONField(default=dict)),
                ('category_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_owner', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('token_date', models.DateTimeField(default=datetime.datetime(2024, 1, 30, 6, 8, 28, 221986, tzinfo=datetime.timezone.utc))),
                ('token_expires', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_type', models.CharField(max_length=255)),
                ('user_data', models.JSONField(default=dict)),
                ('user_date', models.DateTimeField(default=datetime.datetime(2024, 1, 30, 6, 8, 28, 221986, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
